"""
Tokenization and Token IDs

This script demonstrates:
1. Regex-based word tokenization
2. Building a vocabulary
3. Creating a simple tokenizer class
4. Comparison with tiktoken (BPE)
"""

path = "The_Gift_of_the_Magi.txt"

try:
  with open(path, "r", encoding="utf-8") as file:
    data = file.read()
  print(data[:50])
except FileNotFoundError:
  print(f"Error: The file '{path}' was not found")

print(len(data))

"""For tokenization the "re" module of python is used"""

import re

test_tokens_with_spaces = re.split(r'(\s)', data) #capture the whitespaces as tokens
print(f"Tokens with spaces: {test_tokens_with_spaces[:20]}")

test_tokens_without_spaces = re.split(r'\s', data) #whitespaces are used a seperator
print(f"Tokens without spaces: {test_tokens_without_spaces[:20]}")

"""*   Removing whitespaces depends on the task. If the model is sensitive to the exact structure of the text then keeping whitespaces are useful. Eg: Python code
*   For normal tasks removing whitespaces reduces the memory and computation required.




"""

# As the text contains punctuations as well we need to split the tokens taking into account of the punctiations
# tokens = re.split(r'([,.:;?_!"()\'-]|--|\s)', data) #Wrapped in parentheses → capturing group, So the separators are included in the output tokens
tokens = re.split(r'([,.:;?_!"()\'\-–—]|\s)', data)
print(tokens[:30])

print(len(tokens))

final_tokens = [t.strip() for t in tokens if t.strip()] #Removes empty tokens along with the leading and trailing spaces in each token
print(final_tokens[:30])

print(f"Total tokens: {len(final_tokens)}")

"""# **Converting Tokens to Token IDs**

Each unique token is mapped to an unique integer called Token ID.

We'll use:

*   Set to get unique tokens
*   Dictionay to map tokens to token ids

We'll create a Tokenizer class consisting of two parts encoder and decoder:
* Encoder: Text -> Tokens -> Token Ids
* Decoder: Token Ids -> Tokens -> Text
"""

words = sorted(set(final_tokens))
print(len(words))
print(words)

vocabulary = {word: id for id, word in enumerate(words)} #A dictionary containing tokens along with their token Ids

for i, word in enumerate(vocabulary.items()):
  print(word)
  if i >= 30:
    break

"""This vocabulary contain words from only the given data "The gift of magi". If during encoding we encounter words which are not present in the vocabulary we replace those words with special tokens.

Special Context tokens:
* **<|unk|>** : Used to encode unknown words
* **<|endoftext|>** : Used to seperate different text sources
"""

words.extend(["<|endoftext|>", "<|unk|>"])

vocabulary = {word: id for id, word in enumerate(words)}

for i, item in enumerate(list(vocabulary.items())[-3:]):
  print(item)

class SimpleTokenizerV1:
  def __init__(self, vocabulary):
    self.str_to_int = vocabulary
    self.int_to_str = {id:word for word, id in vocabulary.items()}

  def encode(self, text):
    tokens = re.split(r'([,.:;?_!"()\'\-–—]|\s)', text) # splitting the tokens

    final_tokens = [item.strip() for item in tokens if item.strip()] #Removing spaces
    final_tokens = [item if item in self.str_to_int else "<|unk|>" for item in final_tokens]

    #From the given input text we assign token ids from the vocabulary that we have created
    ids = [self.str_to_int[i] for i in final_tokens]

    return ids

  def decode(self, ids):
    text = " ".join([self.int_to_str[i] for i in ids])
    #Replace spaces before the punctuations in the text
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
    return text

"""Testing the Tokenizer class on random input text"""

tokenizer = SimpleTokenizerV1(vocabulary)

text = """The magi, as you know, were wise men—wonderfully wise men—who brought
gifts to the Babe in the manger. They invented the art of giving
Christmas presents.
"""
ids1 = tokenizer.encode(text)
print(f'Text 1 encodings: {ids1}')
#Now if a word is not present in the vocabulary it will be replaced with <|unk|> token

text1 = """"Natural Language Processing (NLP) is a fascinating field! It involves breaking down
text into smaller units—tokens—to make it understandable for machines. For instance, isn't Python
a powerful language for this? 'I love coding,' she said, 'especially with AI.'"
"""
ids2 = tokenizer.encode(text1)
print(f"Text 2 encodings: {ids2}")

#Testing the decoder function by using the inputs generated by the encoder function
decoded_text = tokenizer.decode(ids1)
decoded_text1 = tokenizer.decode(ids2)
print(f'Decoded text 1: {decoded_text}')
print(f'Decoded text 2: {decoded_text1}')

"""So before passing the input to the encoder we need to add the <|endoftext|> token at the end of every text source.

GPTs use Byte Pair Encoding method to encode tokens and does not use <|unk|> or any other token, only the <|endoftext|> token.

# **Different Tokenization algorithms**

- Word based Tokenization
- Sub-Word based Tokenization
- Character based Tokenization

**Subword Based Tokenization** is used by GPT2 and GPT3 for encoding and decoding which is also called as **Byte Pair Encoding**

**Tiktoken** is a Byte pair encoder library used in GPTs
"""

#!pip install tiktoken

import importlib
import tiktoken

print(importlib.metadata.version("tiktoken"))

tokenizer = tiktoken.get_encoding('o200k_base') #o200k_base: Used by gpt-4o, gpt-4.1

text = """"The night train rattled through the silent valley,
its windows glowing like floating lanterns. Somewhere beyond the hills,
a distant dog barked, breaking the stillness for just a moment.
<|endoftext|> She opened the old notebook and found a pressed leaf between
the pages. It crumbled softly in her fingers, as if time itself had turned
into dust."""

tokens = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(tokens)

print(tokenizer.decode(tokens))