# -*- coding: utf-8 -*-
"""Simplified_Attention_Mechanism.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11te97WBHNYZ9ltHbS54XS40KVEMAHtr8

# Implementing Simplified Attention Mechanism without trainable weights

This is not real Transformer attention.

Simplified Self-Attention (No Trainable Q, K, V)

This script demonstrates:
1. Creating token + positional embeddings
2. Computing dot-product attention
3. Applying softmax normalization
4. Generating context vectors

Creating the embedding vector
"""

try:
  with open("The_Time_Machine.txt", "r", encoding="utf-8") as file:
    data = file.read()
except FileNotFoundError:
    raise FileNotFoundError("The_Time_Machine.txt not found in the current directory.")

import tiktoken
import torch
from torch.utils.data import Dataset, DataLoader

class LlmDataset(Dataset):
  """
  Creates input–target token sequences using a sliding window.
  Each input sequence predicts the next token sequence.
  """
  def __init__(self, txt, context_length, stride):
    self.input_ids = []
    self.target_ids = []

    #Tokenization step
    tokenizer = tiktoken.get_encoding('o200k_base')
    token_ids = tokenizer.encode(txt, allowed_special={'<|endoftext|>'})

    # Sliding window to group the sentences into overlapping sequences of context_length
    for i in range(0, len(token_ids)-context_length, stride):
      input_seq = token_ids[i:i+context_length]
      target_seq = token_ids[i+1:i+context_length+1]
      self.input_ids.append(torch.tensor(input_seq))
      self.target_ids.append(torch.tensor(target_seq))

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, ids):
    return self.input_ids[ids], self.target_ids[ids]

def create_dataloader(txt, batch_size=8, context_length=256, drop_last=True, shuffle=True, stride=128, num_workers=0):
  dataset = LlmDataset(txt, context_length, stride)

  dataloader = DataLoader(
      dataset,
      shuffle=shuffle,
      drop_last = drop_last,
      batch_size = batch_size,
      num_workers = num_workers
  )

  return dataloader

import torch

# o200k_base vocabulary has a size of approx 200k
vocab_size = 200000
embedding_dim = 4

torch.manual_seed(123)
token_embedding_layer = torch.nn.Embedding(vocab_size, embedding_dim)
#Creates a matrix of 200k x 4 dimension where each row repesents a token embedding

data_loader = create_dataloader(data, batch_size=1, context_length=6, stride=3, shuffle=False)

data_iter = iter(data_loader)
first_batch = next(data_iter)

print(first_batch)

# Token Embeddings
token_embeddings = token_embedding_layer(first_batch[0])

print(token_embeddings.shape)

context_length = 6
output_dim = 4

positional_embedding_layer = torch.nn.Embedding(context_length, output_dim)

pos_embedding = positional_embedding_layer(torch.arange(context_length))
print(pos_embedding.shape)

# Input Embeddings
input_embeddings = token_embeddings + pos_embedding
print(input_embeddings.shape)

print(input_embeddings[0])

"""Calculating Attention Scores"""

T = input_embeddings.shape[1]
attention_scores = torch.empty(T, T) # A 6x6 matrix as one input contain 6 tokens

d = input_embeddings.shape[-1]
attention_scores = (input_embeddings[0] @ input_embeddings[0].T) / torch.sqrt(torch.tensor(d, dtype=torch.float32))
# Scaling prevents large dot products that push softmax into extremely sharp distributions.

"""Normalize the attention scores using softmax function"""

import torch.nn.functional as F

# As Each row = similarity of one token with all tokens. So we apply softmax along the key dimension (rows sum to 1).
attention_weights = F.softmax(attention_scores, dim=1)
print(attention_weights)

"""Generating the Context Vector"""

context_vector = attention_weights @ input_embeddings[0]
print(context_vector)

"""These context vectors represent weighted combinations of all tokens in the sequence. Each token attends to every other token based on dot-product similarity."""